CLASS zcl_legacy_call DEFINITION
  PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    METHODS call_legacy.
ENDCLASS.

CLASS zcl_legacy_call IMPLEMENTATION.

  METHOD call_legacy.
    " Insecure call
    CALL FUNCTION 'Z_LEGACY_CREATE_TRAVEL'
      EXPORTING iv_data = 'TEST'.
  ENDMETHOD.

ENDCLASS.

