services:

  #################################################################################
  # SAP ABAP Cloud Developer Trial container: 
  #   https://hub.docker.com/r/sapse/abap-cloud-developer-trial
  #################################################################################
  # Corresponding docker command:
  # docker run --stop-timeout 3600 -it --name a4h -h vhcala4hci  sapse/abap-cloud-developer-trial:2023 -agree-to-sap-license
  sap:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: sapse/abap-cloud-developer-trial:2023
    ports:
      - "3200:3200"
      - "3300:3300"
      - "8443:8443"
      - "30213:30213"
      - "50000:50000"
      - "50001:50001"
    tty: true
    container_name: a4h
    hostname: vhcala4hci
    stop_grace_period: 2h
    command: [ "-agree-to-sap-license", "-skip-limits-check", "-skip-hostname-check"]
    sysctls:
      kernel.shmmni: 32768